name: Build 3.12 linux
on: workflow_dispatch
jobs:
  build:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip wheel "fairseq @ git+https://github.com/One-sixth/fairseq.git"
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        with:
          name: Linux whl
          path: fairseq-*.whl
          if-no-files-found: error
